# Generated by Django 5.0.2 on 2024-02-07 08:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lobby', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lobby',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('secret_key', models.CharField(max_length=6)),
                ('purpose', models.TextField(default='', max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='participant',
            name='lobby',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='lobby.lobby'),
            preserve_default=False,
        ),
    ]
